#!/bin/bash
echo -e "\033[1;4;93mTest1: Test stdin redirection\033[0m"
echo "cat < files/aaa" > shell-in
echo "cat < files/aaa" > csh-in
/bin/sh < csh-in > csh-out
../shell < shell-in > shell-out

diff csh-out shell-out 
if [ $? -ne 0 ]
then
  echo -e "\033[1;31m$0 Failed\033[0m"
  exit -1
fi
echo -e "\033[1;32m$0 Passed\033[0m"
exit 0
