#!/bin/bash

rm -f csh-out shell-out
echo -e "\033[1;4;93mTest_envExpand2: Environment - Variable Expansion\033[0m"
echo "setenv C ap" > shell-in
echo "setenv D le" >> shell-in
echo "echo I like \${C}p\${D}" >> shell-in

../shell < shell-in > shell-out

grep "I like apple" shell-out 
if [ $? -ne 0 ]
then
    echo -e "\033[1;31m$0 Failed\033[0m"
    exit -1
fi
echo -e "\033[1;32m$0 Passed\033[0m"
exit 0
