#!/bin/bash

rm -f shell-out
echo -e "\033[1;4;93mTest_setenv1: Enviroment: Set variable\033[0m"

echo "setenv aaa bbbb" > shell-in
echo "printenv" >> shell-in

../shell < shell-in > shell-out

grep aaa=bbbb shell-out > out 2>&1
if [ $? -ne 0 ]
then
    echo -e "\033[1;31m$0 Failed\033[0m"
    exit -1
fi
echo -e "\033[1;32m$0 Passed\033[0m"
exit 0
