#!/bin/bash

rm -f csh-out shell-out
echo -e "\033[1;4;93mTest10: Background\033[0m"
echo "sleep 5 &" > shell-in
echo "touch bgfile" >> shell-in
../shell < shell-in > shell-out &

sleep 1
if [ $? -ne 0 ]
then
  echo -e "\033[1;31m$0 Failed\033[0m"
  exit -1
fi
echo -e "\033[1;32m$0 Passed\033[0m"
exit 0
