#!/bin/bash

rm -f csh-out shell-out "hello world"
echo -e "\033[1;4;93mTest_quotes3: touch \"hello world\"\033[0m"

echo "touch \"hello world\"" > shell-in
echo "ls" >>  shell-in

../shell < shell-in > shell-out 2>&1

if [ ! -f "hello world" ]
then
    echo -e "\033[1;31m$0 Failed\033[0m"
    exit -1
fi
echo -e "\033[1;32m$0 Passed\033[0m"
exit 0
