#!/bin/bash

rm -f csh-out shell-out
echo -e "\033[1;4;93mTest_escape: Escape Chars\033[0m"
echo "echo lll\< kkkk\\\\\\ uuuu\&" > shell-in

../shell < shell-in > shell-out 2>&1

grep "lll< kkkk[\] uuuu&" shell-out 
if [ $? -ne 0 ]
then
    echo -e "\033[1;31m$0 Failed\033[0m"
    exit -1
fi
echo -e "\033[1;32m$0 Passed\033[0m"
exit 0
