#!/bin/bash

rm -f csh-out shell-out
echo -e "\033[1;4;93mTest_quotes2: ls \"command.cc Makefile\"\033[0m"
echo "ls file1.cc files" > shell-in
echo "ls \"file1.cc files\"" >> shell-in

echo "ls file1.cc files" >  csh-in
echo "ls \"file1.cc files\"" >> csh-in

/bin/sh < csh-in > csh-out 2>&1
../shell < shell-in > shell-out 2>&1

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo -e "\033[1;31m$0 Failed\033[0m"
    exit -1
fi
echo -e "\033[1;32m$0 Passed\033[0m"
exit 0
