#!/bin/bash

rm -f csh-out shell-out
echo -e "\033[1;4;93mTest_envExpand1: Environment - Variable Expansion\033[0m"
echo "setenv A hello" > shell-in
echo "setenv B world" >> shell-in
echo "echo \${A} \${B}" >> shell-in
echo "A=hello" > csh-in
echo "B=world" >> csh-in
echo "echo \${A} \${B}" >> csh-in

/bin/sh < csh-in > csh-out 2>&1
../shell < shell-in > shell-out

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo -e "\033[1;31m$0 Failed\033[0m"
    exit -1
fi
echo -e "\033[1;32m$0 Passed\033[0m"
exit 0
