#!/bin/bash
echo -e "\033[1;4;93mTest_tilde: Tilde Expansion\033[0m"

echo "ls ~ > out1" > csh-in
echo "ls ~cs180 >> out1" >> csh-in
echo "ls ~cs180/share >> out1" >> csh-in

echo "ls ~ > out2" > shell-in
echo "ls ~cs180 >> out2" >> shell-in
echo "ls ~cs180/share >> out2" >> shell-in

/bin/bash < csh-in > csh-out 
../shell < shell-in > shell-out 


diff out1 out2 > /dev/null 2>&1
if [ $? -ne 0 ]
then
    echo -e "\033[1;31m$0 Failed\033[0m"
    rm -fr csh-in csh-out shell-in shell-out out1 out2
    exit -1
fi
echo -e "\033[1;32m$0 Passed\033[0m"
rm -fr csh-in csh-out shell-in shell-out out1 out2
exit 0
